site_name: Siddhi-Map-Text
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi Map Text: index.md
- License: license.md
- API Docs:
  - 1.0.3-SNAPSHOT: api/1.0.3-SNAPSHOT.md
theme: material
